from django.urls import path
from . import views

urlpatterns =[
	path('',views.userLogin),
	path('logout',views.userLogout),
	path('register/',views.registration),
	path('hr_home',views.redirect_hr_home),
	path('project_manager_home',views.redirect_project_manager_home),
	path('employee_home',views.redirect_employee_home),
	path('employee_view',views.employee_view),
	path('candidate_register/',views.candidateRegistration),
	path('candidate_view/',views.candidate_view),
	path('candidate_resume/',views.candidate_resume),
	path('questionpaper/',views.addQuestion),
	path('question_view/',views.onlineExam),
	path('mocktest/',views.mockTest),
	path('mockdisplay/',views.mockDisplay),
	path('payment/',views.payment),
	path('emp_profile/',views.employee_profile),
	path('edit/',views.edit),
	path('delete/',views.delete),
	path('interview/',views.interview),
	path('exam_detail/',views.exam_detail),
	path('intimation/',views.intimationDetails),
	path('leave_type/',views.leaveType),
	path('leaveform/', views.leaveApply),
	path('assign/', views.assign),
	path('projectreg/',views.projectReg),
	path('taskadd/', views.taskAdd),
    path('complaintreg/',views.complaintReg),
	path('evaluation/', views.performanceEvaluation),
	path('vacancy/',views.vaccancy),
	path('dept/', views.dept),
	path('leave_view/',views.leaveReport),
	path('complaint_view/',views.complaintReport),
	path('callletter/',views.callLetter),
	# path('payroll/', views.payroll)

]