# Generated by Django 2.2.4 on 2019-09-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=15)),
                ('year_of_pass', models.IntegerField()),
                ('experience', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(max_length=20)),
                ('company_estb_year', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('website', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CostEstimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_cost', models.IntegerField()),
                ('hardware_cost', models.IntegerField()),
                ('equipment_cost', models.IntegerField()),
                ('total_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_image', models.FileField(upload_to='pictures/')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('dob', models.DateField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=15)),
                ('emp_qualification', models.CharField(max_length=25)),
                ('emp_experience', models.CharField(max_length=25)),
                ('salary', models.CharField(max_length=25)),
                ('join_date', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ExamDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_startdate', models.DateField()),
                ('exam_enddate', models.DateField()),
                ('exam_starttime', models.TimeField()),
                ('exam_endtime', models.TimeField()),
                ('exam_duration', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=20)),
                ('to_address', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mock_question', models.CharField(max_length=50)),
                ('option1', models.CharField(max_length=20)),
                ('option2', models.CharField(max_length=20)),
                ('option3', models.CharField(max_length=20)),
                ('option4', models.CharField(max_length=20)),
                ('mock_answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50)),
                ('project_sponser', models.CharField(max_length=50)),
                ('project_manger', models.CharField(max_length=25)),
                ('project_cost', models.IntegerField()),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('project_expense', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('option1', models.CharField(max_length=20)),
                ('option2', models.CharField(max_length=20)),
                ('option3', models.CharField(max_length=20)),
                ('option4', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_req', models.CharField(max_length=50)),
                ('software_req', models.CharField(max_length=50)),
                ('equipment_req', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50)),
                ('task_priority', models.CharField(max_length=25)),
                ('task_start_date', models.DateField()),
                ('task_end_date', models.DateField()),
                ('team_lead', models.CharField(max_length=50)),
                ('fk_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Vacany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_vacanies', models.IntegerField()),
                ('dept_name', models.CharField(max_length=25)),
                ('post', models.CharField(max_length=25)),
                ('emp_qualification', models.CharField(max_length=25)),
                ('emp_experience', models.CharField(max_length=25)),
                ('time_period', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_lead', models.CharField(max_length=25)),
                ('reminder', models.DateField(max_length=25)),
                ('fk_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.EmployeeProfile')),
                ('fk_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.TaskAdd')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='file/')),
                ('fk_candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('rank', models.CharField(max_length=10)),
                ('fk_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAllocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=25)),
                ('dept', models.CharField(max_length=25)),
                ('task_title', models.CharField(max_length=25)),
                ('resource_type', models.CharField(max_length=25)),
                ('resource_available', models.CharField(max_length=25)),
                ('resource_allocated', models.CharField(max_length=25)),
                ('fk_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Project')),
                ('fk_resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_title', models.CharField(max_length=20)),
                ('fk_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.CompanyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=25)),
                ('emp_dept', models.CharField(max_length=25)),
                ('date', models.DateField(max_length=25)),
                ('project', models.CharField(max_length=25)),
                ('emp_duty', models.CharField(max_length=100)),
                ('emp_strength', models.CharField(max_length=75)),
                ('emp_weakness', models.CharField(max_length=75)),
                ('plan_to_improve', models.CharField(max_length=75)),
                ('fk_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.EmployeeProfile')),
                ('fk_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('fk_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.EmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Intimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50)),
                ('intimation_date', models.DateField()),
                ('intimation_description', models.CharField(max_length=60)),
                ('fk_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.EmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(max_length=20)),
                ('interview_Date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interview_location', models.CharField(max_length=20)),
                ('fk_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_available', models.IntegerField()),
                ('leave_taken', models.IntegerField()),
                ('leave_remains', models.IntegerField()),
                ('leave_type', models.CharField(max_length=50)),
                ('from_date', models.DateField(max_length=50)),
                ('to_date', models.DateField(max_length=50)),
                ('no_of_days', models.IntegerField()),
                ('leave_reason', models.CharField(max_length=50)),
                ('fk_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.EmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=25)),
                ('e_desgination', models.CharField(max_length=25)),
                ('e_dept', models.CharField(max_length=25)),
                ('e_addr', models.CharField(max_length=25)),
                ('e_phone', models.IntegerField()),
                ('c_name', models.CharField(max_length=25)),
                ('complaint_desg', models.CharField(max_length=25)),
                ('complaint_dept', models.CharField(max_length=25)),
                ('compaint_description', models.CharField(max_length=60)),
                ('date_of_incident', models.DateField()),
                ('time_of_incident', models.TimeField()),
                ('fk_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.EmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateExperiance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=15)),
                ('period', models.IntegerField()),
                ('fk_candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Candidate')),
                ('fk_resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='CallLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=20)),
                ('join_date', models.DateField()),
                ('join_time', models.TimeField()),
                ('fk_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Candidate')),
            ],
        ),
    ]
