# Generated by Django 2.2.4 on 2019-09-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='login',
            name='fk_role_id',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='fk_login',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hrapp.Login'),
        ),
    ]
