# Generated by Django 2.2.4 on 2019-09-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='password',
        ),
    ]
