# Generated by Django 2.2.4 on 2019-11-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceallocate',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='resourceallocate',
            name='resource_allocated',
        ),
        migrations.RemoveField(
            model_name='resourceallocate',
            name='resource_available',
        ),
        migrations.RemoveField(
            model_name='resourceallocate',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='resourceallocate',
            name='task_title',
        ),
    ]
