# Generated by Django 2.2.4 on 2019-09-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0002_auto_20190926_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_expense',
        ),
    ]
