# Generated by Django 2.2.4 on 2019-09-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0002_auto_20190926_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='fk_role_id',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='fk_login',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hrapp.Login'),
        ),
    ]
