# Generated by Django 2.2.4 on 2019-10-03 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0003_remove_project_project_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='rank',
        ),
        migrations.AddField(
            model_name='result',
            name='fk_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hrapp.MockTest'),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='dept',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='remarks',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='fk_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrapp.Login'),
        ),
    ]
